In [145]:
import pandas as pd

In [146]:
# loading url of party control 1933-2010 from southeast missoury state univerity
url_semo = 'http://cstl-cla.semo.edu/rdrenka/ui320-75/presandcongress.asp'

In [147]:
# Creating a dataframe 
list_semo = pd.read_html(url_semo)

# DataFrame
df = list_semo[0]

#### Cleaning Data

In [148]:
list_del = [0,1,41,42]

In [149]:
# Create a list of range 2 to 22 inclusive 
list_range = list(range(2,23))

In [150]:
# extend first list to the range list
list_del.extend(list_range)

In [151]:
# drop the indices in our dataframe using list_del list 
party_shutdown_df = df.drop(df.index[list_del])

In [152]:
party_with_headers = party_shutdown_df.rename(columns={
    0:"years",1:"president",2:"party_president",4:"house_dem_seats",5:"house_rep_seats",6:"house_other_seats",
    7:"senate_dem_seats",8:"senate_rep_seats",9:"senate_other_seats",10:"gov_status"
})

# delete column with header '3'
del party_with_headers[3]

In [153]:
# resetting dataframe index 
party_with_headers.reset_index(drop=True)

,years,president,party_president,house_dem_seats,house_rep_seats,house_other_seats,senate_dem_seats,senate_rep_seats,senate_other_seats,gov_status
0,1975-76,Ford,R,291,144,0,61.0,38,1.0,divided
1,1977-78,Carter,D,292,143,0,62.0,38,0.0,unified
2,1979-80,Carter,D,277,158,0,59.0,41,0.0,unified
3,1981-82,Reagan,R,243,192,0,47.0,53,0.0,divided (HR)
4,1983-84,Reagan,R,269,166,0,46.0,54,0.0,divided (HR)
5,1985-86,Reagan,R,253,182,0,47.0,53,0.0,divided (HR)
6,1987-88,Reagan,R,258,177,0,55.0,45,0.0,divided
7,1989-90,"Bush, GHW",R,260,175,0,55.0,45,0.0,divided
8,1991-92,Bush,R,267,167,1,56.0,44,0.0,divided
9,1993-94,Clinton,D,258,176,1,57.0,43,0.0,unified
10,1995-96,Clinton,D,202,232,1,46.0,54,0.0,divided
11,1997-98,Clinton,D,206,228,1,45.0,55,0.0,divided
12,1999-2000,Clinton,D,211,223,1,45.0,55,0.0,divided
13,2001-02,"Bush, GW",R,212,221,2,50.0,49*,1.0,divided
14,2003-04,"Bush, GW",R,204,228,3,48.0,51,1.0,unified
15,2005-06,"Bush, GW",R,200,234,1,45.0,55,0.0,unified
16,2007-08,"Bush, GW",R,231,204,0,51.0,49,0.0,divided
17,2009-10,Obama,D,257,178,0,60.0,40,0.0,unified

In [154]:
# checking if there is any NaN value left in the dataframe 
party_with_headers.isnull().values.any()

False

In [155]:
# looking up types of columns in the dataframe
party_with_headers.dtypes

years                  object
president              object
party_president        object
house_dem_seats        object
house_rep_seats        object
house_other_seats      object
senate_dem_seats      float64
senate_rep_seats       object
senate_other_seats    float64
gov_status             object
dtype: object

In [168]:
# create a copy of dataframe to change types
party_df_types = party_with_headers

In [169]:
# Converting three series to numerics
party_df_types['house_dem_seats'] = pd.to_numeric(party_df_types['house_dem_seats'])
party_df_types['house_rep_seats'] = pd.to_numeric(party_df_types['house_rep_seats'])
party_df_types['house_other_seats'] = pd.to_numeric(party_df_types['house_other_seats'])

In [170]:
party_df_types.dtypes

years                  object
president              object
party_president        object
house_dem_seats         int64
house_rep_seats         int64
house_other_seats       int64
senate_dem_seats      float64
senate_rep_seats       object
senate_other_seats    float64
gov_status             object
dtype: object

##### 'senate_rep_seats' cannot be changed to float or int yet because of the value '49*'

In [172]:
# using .loc to locate the "49*" value and changing it to '49'
party_df_types['senate_rep_seats'].loc[party_df_types['senate_rep_seats'] == "49*"] = '49'

/Users/ahmedacheikh/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [173]:
party_df_types['senate_rep_seats'] = pd.to_numeric(party_df_types['senate_rep_seats'])

In [174]:
party_df_types.dtypes

years                  object
president              object
party_president        object
house_dem_seats         int64
house_rep_seats         int64
house_other_seats       int64
senate_dem_seats      float64
senate_rep_seats        int64
senate_other_seats    float64
gov_status             object
dtype: object

In [177]:
# resetting index again just because anaconda is confused
party_df_types.reset_index(drop=True)

,years,president,party_president,house_dem_seats,house_rep_seats,house_other_seats,senate_dem_seats,senate_rep_seats,senate_other_seats,gov_status
0,1975-76,Ford,R,291,144,0,61.0,38,1.0,divided
1,1977-78,Carter,D,292,143,0,62.0,38,0.0,unified
2,1979-80,Carter,D,277,158,0,59.0,41,0.0,unified
3,1981-82,Reagan,R,243,192,0,47.0,53,0.0,divided (HR)
4,1983-84,Reagan,R,269,166,0,46.0,54,0.0,divided (HR)
5,1985-86,Reagan,R,253,182,0,47.0,53,0.0,divided (HR)
6,1987-88,Reagan,R,258,177,0,55.0,45,0.0,divided
7,1989-90,"Bush, GHW",R,260,175,0,55.0,45,0.0,divided
8,1991-92,Bush,R,267,167,1,56.0,44,0.0,divided
9,1993-94,Clinton,D,258,176,1,57.0,43,0.0,unified
10,1995-96,Clinton,D,202,232,1,46.0,54,0.0,divided
11,1997-98,Clinton,D,206,228,1,45.0,55,0.0,divided
12,1999-2000,Clinton,D,211,223,1,45.0,55,0.0,divided
13,2001-02,"Bush, GW",R,212,221,2,50.0,49,1.0,divided
14,2003-04,"Bush, GW",R,204,228,3,48.0,51,1.0,unified
15,2005-06,"Bush, GW",R,200,234,1,45.0,55,0.0,unified
16,2007-08,"Bush, GW",R,231,204,0,51.0,49,0.0,divided
17,2009-10,Obama,D,257,178,0,60.0,40,0.0,unified