In [2]:
# Import pandas
import pandas as pd

In [3]:
# The source of the Excel file is:
# https://www.vox.com/policy-and-politics/2018/1/19/16905584/government-shutdown-history-clinton-obama-explained

# Load spreadsheet
xl = pd.ExcelFile("../Input/government_shutdown_stats.xlsx")

# Load a sheet into a DataFrame by name:
shutdown_df = xl.parse(xl.sheet_names[0])

# Print the df
print(shutdown_df)
print()

    shutdown_number   from_date     to_date  length_in_days  \
0                 1  1976-09-30  1976-10-11              12
1                 2  1977-09-30  1977-10-13              14
2                 3  1977-10-31  1977-11-09              10
3                 4  1977-11-30  1977-12-09              10
4                 5  1978-09-30  1978-10-18              19
5                 6  1979-09-30  1979-10-12              13
6                 7  1981-11-20  1981-11-23               4
7                 8  1982-09-30  1982-10-02               3
8                 9  1982-12-17  1982-12-21               5
9                10  1983-11-10  1983-11-14               5
10               11  1984-09-30  1984-10-03               4
11               12  1984-10-03  1984-10-05               3
12               13  1986-10-16  1986-10-18               3
13               14  1987-12-18  1987-12-20               3
14               15  1990-10-05  1990-10-09               5
15               16  1995-11-13  1995-11-19               7
16               17  1995-12-05  1996-01-06              33
17               18  2013-10-01  2013-10-17              17
18               19  2018-01-20  2018-01-22               3
19               20  2018-02-09  2018-02-09               1

   pres_party_in_power      president senate_party_in_power senate_seats  \
0                    R           Ford                     D      62 - 38
1                    D         Carter                     D      59 - 41
2                    D         Carter                     D      59 - 41
3                    D         Carter                     D      59 - 41
4                    D         Carter                     D      59 - 41
5                    D         Carter                     D      58 - 42
6                    R         Reagan                     R      53 - 47
7                    R         Reagan                     R      53 - 47
8                    R         Reagan                     R      53 - 47
9                    R         Reagan                     R      55 - 45
10                   R         Reagan                     R      55 - 45
11                   R         Reagan                     R      55 - 45
12                   R         Reagan                     R      53 - 47
13                   R         Reagan                     D      54 - 46
14                   R  G. H. W. Bush                     D      55 - 45
15                   D        Clinton                     R      53 - 47
16                   D        Clinton                     R      53 - 47
17                   D          Obama                     D      54 - 46
18                   R          Trump                     R      51 - 49
19                   R          Trump                     R      51 - 49

   house_party_in_power house_seats
0                     D   291 - 144
1                     D   292 - 143
2                     D   292 - 143
3                     D   292 - 143
4                     D   292 - 143
5                     D   277 - 158
6                     D   244 - 191
7                     D   244 - 191
8                     D   244 - 191
9                     D   271 - 164
10                    D   270 - 165
11                    D   270 - 165
12                    D   253 - 182
13                    D   258 - 177
14                    D   258 - 176
15                    R   233 - 199
16                    R   235 - 198
17                    R   232 - 200
18                    R   238 - 193
19                    R   238 - 193

In [6]:
shutdown_df

,shutdown_number,from_date,to_date,length_in_days,pres_party_in_power,president,senate_party_in_power,senate_seats,house_party_in_power,house_seats
0,1,1976-09-30,1976-10-11,12,R,Ford,D,62 - 38,D,291 - 144
1,2,1977-09-30,1977-10-13,14,D,Carter,D,59 - 41,D,292 - 143
2,3,1977-10-31,1977-11-09,10,D,Carter,D,59 - 41,D,292 - 143
3,4,1977-11-30,1977-12-09,10,D,Carter,D,59 - 41,D,292 - 143
4,5,1978-09-30,1978-10-18,19,D,Carter,D,59 - 41,D,292 - 143
5,6,1979-09-30,1979-10-12,13,D,Carter,D,58 - 42,D,277 - 158
6,7,1981-11-20,1981-11-23,4,R,Reagan,R,53 - 47,D,244 - 191
7,8,1982-09-30,1982-10-02,3,R,Reagan,R,53 - 47,D,244 - 191
8,9,1982-12-17,1982-12-21,5,R,Reagan,R,53 - 47,D,244 - 191
9,10,1983-11-10,1983-11-14,5,R,Reagan,R,55 - 45,D,271 - 164
10,11,1984-09-30,1984-10-03,4,R,Reagan,R,55 - 45,D,270 - 165
11,12,1984-10-03,1984-10-05,3,R,Reagan,R,55 - 45,D,270 - 165
12,13,1986-10-16,1986-10-18,3,R,Reagan,R,53 - 47,D,253 - 182
13,14,1987-12-18,1987-12-20,3,R,Reagan,D,54 - 46,D,258 - 177
14,15,1990-10-05,1990-10-09,5,R,G. H. W. Bush,D,55 - 45,D,258 - 176
15,16,1995-11-13,1995-11-19,7,D,Clinton,R,53 - 47,R,233 - 199
16,17,1995-12-05,1996-01-06,33,D,Clinton,R,53 - 47,R,235 - 198
17,18,2013-10-01,2013-10-17,17,D,Obama,D,54 - 46,R,232 - 200
18,19,2018-01-20,2018-01-22,3,R,Trump,R,51 - 49,R,238 - 193
19,20,2018-02-09,2018-02-09,1,R,Trump,R,51 - 49,R,238 - 193